spring:
  web:
    locale: nl_NL
    locale-resolver: fixed

salesforce:
  enabled: false
  api:
    baseUrl: ${SALESFORCE_API_BASE_URL}
    clientId: ${SALESFORCE_API_CLIENT_ID}
    clientSecret: ${SALESFORCE_API_CLIENT_SECRET}

pirlewiet:
    email: ${PIRLEWIET_EMAIL}
    pdEmail: ${PIRLEWIET_PD_EMAIL}
    year: ${PIRLEWIET_YEAR}

brevo:
  api:
    key: ${BREVO_API_KEY}