package be.pirlewiet.registrations.domain.exception;

public enum ErrorCode {
	
	APPLICATION_NOT_FOUND,
	APPLICATION_HOLIDAY_NONE,
	APPLICATION_HOLIDAY_MIXED,
	APPLICATION_HOLIDAY_NOT_FOUND,
	APPLICATION_CONTACT_INCOMPLETE,
	APPLICATION_QLIST_INCOMPLETE,
	APPLICATION_NO_ENROLLMENTS,
	
	PARTICIPANT_DATA_GIVEN_NAME_MISSING,
	PARTICIPANT_DATA_FAMILY_NAME_MISSING,
	PARTICIPANT_DATA_BIRTHDAY_MISSING,
	PARTICIPANT_DATA_GENDER_MISSING,
	PARTICIPANT_DATA_PHONE_MISSING,

	PARTICIPANT_MEDIC_QUESTION_MISSING

}
