<h2>Detail Deelnemer</h2>
<table>
    <tr>
        <td>voornaam:</td>
        <td>${deelnemer.voornaam}</td>
    </tr>
    <tr>
        <td>familienaam:</td>
        <td>${deelnemer.familienaam}</td>
    </tr>
    <tr>
        <td>geboortedatum:</td>
        <td>${deelnemer.geboortedatum}</td>
    </tr>
    <tr>
        <td>rijksregisternr:</td>
        <td>${deelnemer.rijksregisternr}</td>
    </tr>
    <tr>
        <td>gsmnr:</td>
        <td>${deelnemer.gsmnr}</td>
    </tr>
    <tr>
        <td>geslacht:</td>
        <td>${deelnemer.geslacht}</td>
    </tr>
    <tr>
        <td>straat:</td>
        <td>${deelnemer.adres.straat}</td>
    </tr>
    <tr>
        <td>nummer</td>
        <td>${deelnemer.adres.nummer}</td>
    </tr>
    <tr>
        <td>postcode:</td>
        <td>${deelnemer.adres.postcode}</td>
    </tr>
    <tr>
        <td>gemeente:</td>
        <td>${deelnemer.adres.gemeente}</td>
    </tr>
</table>